services:

  postrgre-db:
    image: postgres:15
    container_name: postrgre
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart: always

  fastapi-app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - 8000:8000
    depends_on:
      - postrgre-db
      - redis
    restart: always
    command: bash -c "alembic upgrade head 
        && python main.py"

volumes:
  postgres_data: {}