"""'migrate'

Revision ID: da539b2f4557
Revises: 
Create Date: 2024-10-24 09:09:48.785795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da539b2f4557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('date_registration', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('refresh_token', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('invited',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_inviting_id', sa.Integer(), nullable=True),
                    sa.Column('user_invited_id', sa.Integer(), nullable=True),
                    sa.Column('referal_head', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_invited_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_inviting_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('referal_head'),
                    sa.UniqueConstraint('user_invited_id')
                    )
    op.create_table('referal_links',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('link', sa.String(), nullable=True),
                    sa.Column('life_time', sa.DateTime(), nullable=False),
                    sa.Column('used', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('link'),
                    sa.UniqueConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referal_links')
    op.drop_table('invited')
    op.drop_table('users')
    # ### end Alembic commands ###
